name: Deploy Nightly Nuget Package

on:
  push:
    branches:
      - dev

jobs:
  deploy_nu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.102
    - name: Build with dotnet
      run: dotnet build --configuration Release
