name: Deploy Nightly Nuget Package

on:
  push:
    branches:
      - dev

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.102
        source-url: https://nuget.pkg.github.com/myty/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Build
      run: dotnet build --configuration Release ./src/Nu.Plugin/Nu.Plugin.csproj
    - name: Create Nuget Package
      run: dotnet pack --configuration Release ./src/Nu.Plugin/Nu.Plugin.csproj
    - name: Publish Nuget Package to GPR
      run: dotnet nuget push ./src/Nu.Plugin/bin/Release/*.nupkg